### ISSUE TITLE
Bridge module 'set' parameter to accept a list of strings

### ISSUE THREAD

**Issue by celyn-sdn** [ansible-collections/openvswitch.openvswitch#117]
##### SUMMARY

In the bridge module, the set parameter accepts a string but it would be better if it accepted a list of strings because it can be used to configure several things like the datapath-id, the OpenFlow protocol version, etc..

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openvswitch.openvswitch_bridge.py
##### ADDITIONAL INFORMATION

It would enable the user to set the bridges up more completely than is currently permitted in a single loop.

```yaml
- hosts: ovs
  vars:
    bridges:
      - bridge: ovs-br1
        set: 
          - Bridge ovs-br1 other-config:datapath-id=0000000000000001
          - Bridge ovs-br1 protocols=OpenFlow13
      - bridge: ovs-br2
        set: 
          - Bridge ovs-br2 other-config:datapath-id=0000000000000002
          - Bridge ovs-br2 protocols=OpenFlow13

  - openvswitch.openvswitch.openvswitch_bridge:
      bridge: '{{ item.bridge }}'
      set: '{{ item.set }}'
    become: true
    loop: "{{ bridges }}"
```
