### ISSUE TITLE
Unable to delete key/value pairs in db without specifying value as value is not optional

### ISSUE THREAD

**Issue by markdgray** [ansible-collections/openvswitch.openvswitch#64]
##### SUMMARY
Unable to delete key/value pairs in db without specifying value as value is not optional.

For example:

```
 openvswitch.openvswitch.openvswitch_db:
      table: Open_vSwitch
      record: .
      col: other_config
      key: ca_cert
      state: absent
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openvswitch.openvswitch.openvswitch_db:

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<uid>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### EXPECTED RESULTS
I would expect that the key/value pair would be removed from ovsdb

##### ACTUAL RESULTS
The key/value remains
